spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import:
      - application-storage-${spring.profiles.active}.yml
      - application-client-${spring.profiles.active}.yml