spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}