name: prd-api-deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ closed ] # when PR closed
    paths:
      - 'src/api/**'
      - 'src/core/**'
      - 'src/domain/**'
      - 'src/infrastructure/**'
      - '.github/workflows/prd-api-deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache gradle modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push Docker image to DockerHub
        run: |
          ./gradlew -Ptag=prd :api:jib \
          -Djib.from.image=openjdk:17-jdk-slim \ 
          -Djib.to.image=${{secrets.DOCKER_IMAGE}} \
          -Djib.container.jvmFlags="-Dspring.profiles.active=prd,-Dfile.encoding=UTF-8" \
          -Djib.container.environment="DATASOURCE_URL=${{ secrets.DATASOURCE_URL}},DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }},DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}"